hello: sortmainfinal.o sortfuncsfinal.o
	gcc -o hello sortmainfinal.o sortfuncsfinal.o
sortmainfinal.o: sortmainfinal.c
	gcc -c sortmainfinal.c
sortfuncsfinal.o: sortfuncsfinal.c
	gcc -c sortfuncsfinal.c