repl_c: main_repl_c.o functions_repl_c.o
	gcc main_repl_c.o functions_repl_c.o -o repl_c
	
main_repl_c.o: main_repl_c.c
	gcc -c main_repl_c.c
	
functions_repl_c.o: functions_repl_c.c
	gcc -c functions_repl_c.c
