repl_l: main_repl_l.o functions_repl_l.o
	gcc main_repl_l.o functions_repl_l.o -o repl_l
	
main_repl_l.o: main_repl_l.c
	gcc -c main_repl_l.c
	
functions_repl_l.o: functions_repl_l.c
	gcc -c functions_repl_l.c
